Projects
nerdishbynature/TanukiKit pull request #33
Opened 2017-02-17 10:18 UTC by tiferrei

Here is the PR containing the repo –> project changes, at the moment is failing because I wasn't able to merge or rebase from master, to include the commit requests, required by the tests.

PS: I have no idea how to merge this. `project.pbxproj` is pure hell when it comes to merge conflicts.

2017-02-20 10:49 UTC, pietbrauer commented
Tests seem to fail for macOS:

```bash
CommitTests
❌  fatal error: unexpectedly found nil while unwrapping an Optional value
```

2017-02-20 12:56 UTC, tiferrei commented
Fixed, after this one I'll just open the one for the `login` –> `username` changes, and after that it's pretty much ready for major release?

2017-02-20 13:55 UTC, pietbrauer requested changes
Thanks for the PR! Just some small things. Please make sure tests war written for the new endpoints.

2017-02-20 13:55 UTC, pietbrauer commented on TanukiKit/Project.swift
> +            noteEvents = json["ntoe_events"] as? Bool
Small typo here `ntoe_events` should be `note_events` (`projectHooks` is missing tests)

2017-02-20 13:55 UTC, pietbrauer commented on TanukiKit/Project.swift
> +        //repository = Repository(json["repository"] as? [String: AnyObject] ?? [:])
Please remove the dead code

2017-02-20 13:55 UTC, pietbrauer commented on TanukiKitTests/ProjectTests.swift
> +        // TODO: Finish Parsing tests
Is this still in Progress?

2017-02-20 13:55 UTC, pietbrauer commented on TanukiKitTests/ProjectTests.swift
> +        print("DEBUG: \(event.data!.commits)")
Please remove the debug `print`

2017-02-22 13:02 UTC, tiferrei commented on TanukiKitTests/ProjectTests.swift
> +        // TODO: Finish Parsing tests
Oh I wasn't completely sure wether I should do those parsing tests as they just repeat the commit and event parsing tests? What would you prefer me to do?

2017-02-22 13:48 UTC, pietbrauer commented on TanukiKitTests/ProjectTests.swift
> +        // TODO: Finish Parsing tests
Given that [there was an error](https://github.com/nerdishbynature/TanukiKit/pull/33#discussion_r102021287) in the repetition I would prefer to have tests for that.

2017-02-22 22:45 UTC, tiferrei commented
```log
2017-02-22 22:40:57.828 xcodebuild[16482:31076] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/TanukiKit-fvezsfumqfjrojegffuqyyeakarq/Logs/Test/B5D72806-DA2D-4705-AD6E-CB903AB72D8B/Session-TanukiKitTests-2017-02-22_224056-ZN9N3c.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/TanukiKit-fvezsfumqfjrojegffuqyyeakarq/Logs/Test/B5D72806-DA2D-4705-AD6E-CB903AB72D8B/Session-TanukiKitTests-2017-02-22_224056-ZN9N3c.log}
```

@pietbrauer Travis seems to be having a hard time with this one, took it hours to start and then failed within 5 minutes?

2017-02-27 11:17 UTC, tiferrei commented
@pietbrauer: Am I seeing things, or did that space in the end of the declaration mess up the whole CI process?

2017-02-27 11:18 UTC, pietbrauer commented
No, it messed up Xcode. I just opened the project in Xcode, clicked on the "Fix it" button and the build error went away.

2017-02-27 11:19 UTC, tiferrei commented
Hmm interesting, everything ran perfectly on mine? Even the CI commands.

2017-02-27 13:09 UTC, pietbrauer approved these changes
Great work, don't know why the Xcode Project has so many changes but I'm ok with it.

2017-02-27 13:09 UTC, merged